- hosts: web
  become: true 
  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Run the app container
      community.docker.docker_container:
        name: devops-app
        image: toba44/docker-js
        state: started
        ports:
          - "3000:3000"
